name: "Build on PRs"

on:
  pull_request:

jobs:
  build:
    name: "Build Website"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout main"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "cachix/install-nix-action@v27"
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build Website"
        run: |
          nix-shell -A shell --run "dev-build"

      - name: "Fix Permissions of Website Artifacts"
        run: |
          chmod -c -R +rX "public/" | while read -r line; do
            echo "::warning title=Invalid file permissions automatically fixed::${line}"
          done

      - name: "Upload Website"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "public/"
