name: "Build and Deploy Website"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build Website"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout main"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v14"

      - name: "Use Nix Cache"
        uses: "DeterminateSystems/magic-nix-cache-action@v8"

      - name: "Build Website"
        run: |
          nix-shell -A shell --run "dev-build"

      - name: "Fix Permissions of Website Artifacts"
        run: |
          chmod -c -R +rX "public/" | while read -r line; do
            echo "::warning title=Invalid file permissions automatically fixed::${line}"
          done

      - name: "Upload Website"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "public/"

  deploy:
    name: "Deploy Website"
    needs: "build"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
